language: dart
sudo: required
dart:
- dev
dart_task:
- dartanalyzer
- test: --platform vm
- test: --platform chrome
matrix:
  include:
  - dart: dev
    dart_task: dartfmt
cache:
  directories:
  - $HOME/.pub-cache
