language: dart
sudo: required
dart:
  - stable
  - dev
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer
  - dartfmt
matrix:
  allow_failures:
  - dart: dev
cache:
  directories:
    - $HOME/.pub-cache
script:
  - ./tool/travis.sh