name: statemachine
version: 1.4.3

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/renggli/dart-statemachine
description: A simple, yet powerful state machine framework for Dart supporting
  Flutter and web apps.

environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.3.0
