name: statemachine
version: 1.6.0

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/renggli/dart-statemachine
description: A simple, yet powerful state machine framework for Dart supporting
  Flutter and web apps.

environment:
  sdk: '>=2.4.0 <3.0.0'
dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.4.0
  build_web_compilers: ^2.1.0
