name: statemachine
version: 1.4.1

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/renggli/dart-statemachine
description: A simple, yet powerful state machine framework for Dart supporting
  Flutter and web apps.

environment:
  sdk: ">=2.0.0-dev.69.4 <3.0.0"
dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.3.0
